version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: books
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-books}
      POSTGRES_DB: books
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
