# Generated by Django 4.2.30 on 2026-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field_one',
            field=models.TextField(blank=True, null=True),
        ),
    ]
