# Generated by Django 4.2.30 on 2026-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field_two',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
