# Generated by Django 4.2.30 on 2026-07-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_new_field_one'),
        ('api', '0002_book_new_field_two'),
    ]

    operations = [
    ]
