name: my first github action

on:
  push:
    branches:
      - main

env:
  POSTGRES_USER: books
  POSTGRES_PASSWORD: books
  POSTGRES_DB: books
  DB_HOST: localhost
  DB_PORT: 5432
  DEBUG: True

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: books
          POSTGRES_PASSWORD: books
          POSTGRES_DB: books
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        uses: ./.github/actions/setup-python-deps

      - name: Run tests
        run: |
          python -m pytest api/tests/test_views.py -v

  run-migrations:
    runs-on: ubuntu-latest
    needs: build

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: books
          POSTGRES_PASSWORD: books
          POSTGRES_DB: books
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        uses: ./.github/actions/setup-python-deps

      - name: Run django migrate
        run: |
          python manage.py migrate

  checkmigrations:
    runs-on: ubuntu-latest
    needs: run-migrations

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: books
          POSTGRES_PASSWORD: books
          POSTGRES_DB: books
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        uses: ./.github/actions/setup-python-deps

      - name: Check migrations are in sync
        run: |
          python manage.py makemigrations --check --dry-run